"use client";

import JSZip from "jszip";
import { saveAs } from "file-saver";

import type { BuilderProject } from "./types";

function createAppLayout() {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Generated by Drag and Drop Studio",
  description: "A generated starter exported from the visual builder.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function createGlobalStyles() {
  return `@import "tailwindcss";

:root {
  --background: #f7f4ed;
  --foreground: #101828;
}

* {
  box-sizing: border-box;
}

html,
body {
  min-height: 100%;
}

body {
  margin: 0;
  background: var(--background);
  color: var(--foreground);
  font-family: system-ui, sans-serif;
}
`;
}

function createRendererFile() {
  return `import type { CSSProperties, ReactNode } from "react";

import { project } from "@/lib/project-data";

function buttonVariant(label: string, variant: string, fullWidth?: boolean) {
  const style: CSSProperties = {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    padding: "10px 16px",
    fontSize: 14,
    fontWeight: 600,
    width: fullWidth ? "100%" : undefined,
  };

  if (variant === "secondary") {
    return (
      <button type="button" style={{ ...style, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", color: "var(--builder-foreground)" }}>
        {label}
      </button>
    );
  }

  if (variant === "ghost") {
    return (
      <button type="button" style={{ ...style, color: "var(--builder-muted)", background: "transparent" }}>
        {label}
      </button>
    );
  }

  return (
    <button type="button" style={{ ...style, background: "var(--builder-accent)", color: "var(--builder-accent-contrast)" }}>
      {label}
    </button>
  );
}

function featureLines(value: string) {
  return (
    <ul style={{ display: "grid", gap: 12, listStyle: "none", margin: 0, padding: 0, color: "var(--builder-muted)" }}>
      {value
        .split("\\n")
        .map((item) => item.trim())
        .filter(Boolean)
        .map((item) => (
          <li key={item} style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ width: 10, height: 10, borderRadius: 999, background: "var(--builder-accent)", display: "inline-block" }} />
            <span>{item}</span>
          </li>
        ))}
    </ul>
  );
}

function renderNode(nodeId: string): ReactNode {
  const node = project.nodes[nodeId];
  const children = node.children.map((childId) => renderNode(childId));

  switch (node.type) {
    case "section": {
      const backgrounds: Record<string, CSSProperties> = {
        surface: { background: "var(--builder-surface)", border: "1px solid var(--builder-border)" },
        accent: {
          background: "linear-gradient(135deg, color-mix(in srgb, var(--builder-accent) 16%, white), rgba(255,255,255,0.72))",
          border: "1px solid color-mix(in srgb, var(--builder-accent) 20%, white)",
        },
        transparent: { background: "transparent", border: "1px dashed var(--builder-border)" },
      };

      return (
        <section
          key={node.id}
          style={{
            padding: \`\${node.props.paddingY ?? 48}px \${node.props.inset ? 24 : 0}px\`,
            borderRadius: 20,
            ...backgrounds[\`\${node.props.backgroundStyle ?? "surface"}\`],
          }}
        >
          <div style={{ display: "grid", gap: 16 }}>
            <div>
              <p style={{ margin: 0, fontSize: 14, color: "var(--builder-muted)" }}>Section</p>
              <h3 style={{ margin: "4px 0 0", fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
            </div>
            <div style={{ display: "grid", gap: 16 }}>{children}</div>
          </div>
        </section>
      );
    }
    case "stack":
      return (
        <div key={node.id} style={{ display: "flex", flexDirection: "column", gap: \`\${node.props.gap ?? 18}px\`, alignItems: \`\${node.props.align ?? "stretch"}\` }}>
          {children}
        </div>
      );
    case "grid":
      return (
        <div key={node.id} style={{ display: "grid", gap: \`\${node.props.gap ?? 18}px\`, gridTemplateColumns: \`repeat(\${node.props.columns ?? 3}, minmax(0, 1fr))\` }}>
          {children}
        </div>
      );
    case "hero": {
      const centered = node.props.align === "center";
      return (
        <section
          key={node.id}
          style={{
            borderRadius: 32,
            padding: "40px 32px",
            border: "1px solid var(--builder-border)",
            background: "linear-gradient(135deg, color-mix(in srgb, var(--builder-accent) 12%, white), rgba(255,255,255,0.95))",
            textAlign: centered ? "center" : "left",
          }}
        >
          <span style={{ display: "inline-flex", borderRadius: 999, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.8)", padding: "6px 12px", fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.24em", color: "var(--builder-muted)" }}>
            {\`\${node.props.eyebrow}\`}
          </span>
          <div style={{ marginTop: 24, display: "grid", gap: 16, maxWidth: 760, marginInline: centered ? "auto" : undefined }}>
            <h1 style={{ margin: 0, fontSize: 48, lineHeight: 1.05 }}>{\`\${node.props.title}\`}</h1>
            <p style={{ margin: 0, fontSize: 18, lineHeight: 1.7, color: "var(--builder-muted)" }}>{\`\${node.props.body}\`}</p>
          </div>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 28, justifyContent: centered ? "center" : "flex-start" }}>
            {buttonVariant(\`\${node.props.primaryLabel}\`, "primary")}
            {buttonVariant(\`\${node.props.secondaryLabel}\`, "secondary")}
          </div>
        </section>
      );
    }
    case "text":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.8)", padding: 24 }}>
          <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.75 }}>{\`\${node.props.body}\`}</p>
        </div>
      );
    case "button":
      return (
        <div key={node.id} style={{ padding: 16, borderRadius: 18, border: "1px dashed var(--builder-border)", background: "rgba(255,255,255,0.68)" }}>
          {buttonVariant(\`\${node.props.label}\`, \`\${node.props.variant}\`, Boolean(node.props.fullWidth))}
        </div>
      );
    case "featureGrid":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.82)", padding: 24 }}>
          <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          <div style={{ marginTop: 20 }}>{featureLines(\`\${node.props.features}\`)}</div>
        </div>
      );
    case "statCard":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 20 }}>
          <p style={{ margin: 0, fontSize: 14, color: "var(--builder-muted)" }}>{\`\${node.props.label}\`}</p>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "end", gap: 16, marginTop: 16 }}>
            <p style={{ margin: 0, fontSize: 42, fontWeight: 700 }}>{\`\${node.props.value}\`}</p>
            <span style={{ borderRadius: 999, padding: "6px 12px", background: "color-mix(in srgb, var(--builder-accent) 10%, white)", color: "var(--builder-accent)", fontSize: 12, fontWeight: 700 }}>
              {\`\${node.props.trend}\`}
            </span>
          </div>
        </div>
      );
    case "formCard":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "10px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          <div style={{ display: "grid", gap: 12, marginTop: 20 }}>
            <div style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "14px 16px", color: "var(--builder-muted)" }}>
              Email address
            </div>
            {buttonVariant(\`\${node.props.buttonLabel}\`, "primary", true)}
          </div>
        </div>
      );
    case "pricingCard":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.88)", padding: 24 }}>
          <p style={{ margin: 0, fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--builder-muted)" }}>{\`\${node.props.tier}\`}</p>
          <div style={{ display: "flex", gap: 8, alignItems: "end", marginTop: 12 }}>
            <p style={{ margin: 0, fontSize: 42, fontWeight: 700 }}>{\`\${node.props.price}\`}</p>
            <span style={{ color: "var(--builder-muted)", paddingBottom: 6 }}>/ month</span>
          </div>
          <p style={{ margin: "16px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.tagline}\`}</p>
          <div style={{ marginTop: 20 }}>{buttonVariant(\`\${node.props.cta}\`, "primary", true)}</div>
        </div>
      );
    case "chatInput":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, marginBottom: 16 }}>
            <p style={{ margin: 0, fontWeight: 600 }}>{\`\${node.props.label}\`}</p>
            <span style={{ borderRadius: 999, border: "1px solid var(--builder-border)", padding: "4px 12px", fontSize: 12, color: "var(--builder-muted)" }}>
              AI shell
            </span>
          </div>
          <div style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: 16 }}>
            <p style={{ margin: 0, color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.placeholder}\`}</p>
            <div style={{ display: "flex", justifyContent: "end", marginTop: 16 }}>{buttonVariant(\`\${node.props.buttonLabel}\`, "primary")}</div>
          </div>
        </div>
      );
    case "sidebarShell": {
      const items = \`\${node.props.items}\`
        .split("\\n")
        .map((item) => item.trim())
        .filter(Boolean);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.88)", padding: 18 }}>
          <p style={{ margin: "0 0 16px", fontWeight: 600 }}>{\`\${node.props.title}\`}</p>
          <div style={{ display: "grid", gap: 8 }}>
            {items.map((item) => {
              const active = item === \`\${node.props.highlight}\`;

              return (
                <div key={item} style={{ borderRadius: 16, padding: "10px 12px", color: active ? "var(--builder-accent-contrast)" : "var(--builder-muted)", background: active ? "var(--builder-accent)" : "transparent" }}>
                  {item}
                </div>
              );
            })}
          </div>
        </div>
      );
    }
    default:
      return null;
  }
}

export function ProjectPage({ pageId }: { pageId: string }) {
  const page = project.pages.find((entry) => entry.id === pageId);

  if (!page) {
    return null;
  }

  const style = {
    ["--builder-background" as string]: project.theme.background,
    ["--builder-foreground" as string]: project.theme.foreground,
    ["--builder-muted" as string]: project.theme.muted,
    ["--builder-surface" as string]: project.theme.surface,
    ["--builder-border" as string]: "rgba(16, 24, 40, 0.12)",
    ["--builder-accent" as string]: project.theme.accent,
    ["--builder-accent-contrast" as string]: project.theme.accentContrast,
  } as CSSProperties;

  return (
    <main
      style={{
        ...style,
        minHeight: "100vh",
        background: "radial-gradient(circle at top left, rgba(15, 118, 110, 0.16), transparent 34%), linear-gradient(180deg, #fcfaf6 0%, #efe6d6 100%)",
        padding: "48px 24px 96px",
        color: "var(--builder-foreground)",
        fontFamily: project.theme.fontFamily,
      }}
    >
      <div style={{ maxWidth: 1180, margin: "0 auto", display: "grid", gap: 24 }}>
        {page.rootIds.map((rootId) => renderNode(rootId))}
      </div>
    </main>
  );
}
`;
}

function createReadme(project: BuilderProject) {
  return `# ${project.name}

This starter was generated from Drag and Drop Studio.

## Scripts

- \`pnpm install\`
- \`pnpm dev\`
- \`pnpm build\`

## Included

- Multi-page route generation
- A schema-driven page renderer
- Theme values pulled from the builder project
- Editable page data in \`lib/project-data.ts\`

## Notes

This export keeps the schema and renderer explicit so a developer can continue refining the output instead of untangling opaque generated markup.
`;
}

function createProjectData(project: BuilderProject) {
  return `export const project = ${JSON.stringify(project, null, 2)} as const;
`;
}

function createRouteFile(pageId: string) {
  return `import { ProjectPage } from "@/lib/render-page";

export default function Page() {
  return <ProjectPage pageId="${pageId}" />;
}
`;
}

function createPackageJson(projectName: string) {
  return JSON.stringify(
    {
      name: projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      private: true,
      version: "0.1.0",
      scripts: {
        dev: "next dev",
        build: "next build --webpack",
        start: "next start",
      },
      dependencies: {
        next: "16.2.2",
        react: "19.2.4",
        "react-dom": "19.2.4",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4.2.2",
        "@types/node": "^20.19.37",
        "@types/react": "^19.2.14",
        "@types/react-dom": "^19.2.3",
        tailwindcss: "^4.2.2",
        typescript: "^5.9.3",
      },
    },
    null,
    2,
  );
}

function createTsConfig() {
  return `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
}

function createNextConfig() {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
}

function createPostCssConfig() {
  return `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`;
}

function createNextEnv() {
  return `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;
}

function pagePathToRouteFile(pathname: string) {
  if (pathname === "/") {
    return "app/page.tsx";
  }

  const segments = pathname.replace(/^\//, "").split("/").filter(Boolean);
  return `app/${segments.join("/")}/page.tsx`;
}

export async function exportProjectZip(project: BuilderProject) {
  const zip = new JSZip();

  zip.file("package.json", createPackageJson(project.name));
  zip.file("tsconfig.json", createTsConfig());
  zip.file("next.config.ts", createNextConfig());
  zip.file("postcss.config.mjs", createPostCssConfig());
  zip.file("next-env.d.ts", createNextEnv());
  zip.file("README.md", createReadme(project));
  zip.file(".env.example", "# Add provider credentials here when you wire services in v2.\n");
  zip.file("app/layout.tsx", createAppLayout());
  zip.file("app/globals.css", createGlobalStyles());
  zip.file("lib/project-data.ts", createProjectData(project));
  zip.file("lib/render-page.tsx", createRendererFile());

  for (const page of project.pages) {
    zip.file(pagePathToRouteFile(page.path), createRouteFile(page.id));
  }

  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-starter.zip`);
}
