import type { BuilderProject } from "./types";
import { createStarterRenderSupportFile } from "./starter-render-support";

export interface StarterProjectFile {
  path: string;
  contents: string;
}

function createAppLayout() {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Generated by Drag and Drop Studio",
  description: "A generated starter exported from the visual builder.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function createGlobalStyles() {
  return `@import "tailwindcss";

:root {
  --background: #f7f4ed;
  --foreground: #101828;
}

* {
  box-sizing: border-box;
}

html,
body {
  min-height: 100%;
}

body {
  margin: 0;
  background: var(--background);
  color: var(--foreground);
  font-family: system-ui, sans-serif;
}
`;
}

function createRendererFile() {
  return `import type { CSSProperties, ReactNode } from "react";

import { project } from "@/lib/project-data";
import {
  buttonVariant,
  featureLines,
  parseActivityEntries,
  parseFaqItems,
  parseInfoListItems,
  parseMetricItems,
  parseStepItems,
  parseTable,
  parseTranscript,
  toBuilderThemeStyleVariables,
  toLines,
} from "@/lib/render-support";

function getBlockDataAttributes(node: { id: string; type: string }) {
  return {
    "data-builder-block-type": node.type,
    "data-builder-node-id": node.id,
  };
}

function getRegionDataAttributes(node: { id: string; type: string }, regionId: string) {
  return {
    "data-builder-region-id": regionId,
    "data-builder-region-parent-id": node.id,
    "data-builder-region-parent-type": node.type,
  };
}

function renderNode(nodeId: string): ReactNode {
  const node = project.nodes[nodeId];
  const renderedRegions = Object.fromEntries(
    Object.entries(node.regions).map(([regionId, childIds]) => [regionId, childIds.map((childId) => renderNode(childId))]),
  ) as Record<string, ReactNode[]>;
  const contentChildren = renderedRegions.content ?? [];
  const actionChildren = renderedRegions.actions ?? [];
  const sidebarChildren = renderedRegions.sidebar ?? [];
  const blockDataAttributes = getBlockDataAttributes(node);

  switch (node.type) {
    case "navbar": {
      const links = toLines(\`\${node.props.links}\`);
      const centered = node.props.align === "center";

      return (
        <nav
          key={node.id}
          style={{
            display: "flex",
            flexWrap: "wrap",
            alignItems: "center",
            justifyContent: centered ? "center" : "space-between",
            gap: 16,
            borderRadius: 20,
            border: "1px solid var(--builder-border)",
            background: "rgba(255,255,255,0.92)",
            padding: "18px 20px",
          }}
        >
          <div style={{ fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.18em" }}>
            {\`\${node.props.logo}\`}
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
            {links.map((link) => (
              <span key={link} style={{ borderRadius: 999, border: "1px solid var(--builder-border)", padding: "8px 12px", fontSize: 12, color: "var(--builder-muted)" }}>
                {link}
              </span>
            ))}
          </div>
          {buttonVariant(\`\${node.props.ctaLabel}\`, "primary")}
        </nav>
      );
    }
    case "section": {
      const backgrounds: Record<string, CSSProperties> = {
        surface: { background: "var(--builder-surface)", border: "1px solid var(--builder-border)" },
        accent: {
          background: "linear-gradient(135deg, color-mix(in srgb, var(--builder-accent) 16%, white), rgba(255,255,255,0.72))",
          border: "1px solid color-mix(in srgb, var(--builder-accent) 20%, white)",
        },
        transparent: { background: "transparent", border: "1px dashed var(--builder-border)" },
      };

      return (
        <section
          key={node.id}
          {...blockDataAttributes}
          style={{
            padding: \`\${node.props.paddingY ?? 48}px \${node.props.inset ? 24 : 0}px\`,
            borderRadius: 20,
            ...backgrounds[\`\${node.props.backgroundStyle ?? "surface"}\`],
          }}
        >
          <div style={{ display: "grid", gap: 16 }}>
            <div>
              <p style={{ margin: 0, fontSize: 14, color: "var(--builder-muted)" }}>Section</p>
              <h3 style={{ margin: "4px 0 0", fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
            </div>
            <div {...getRegionDataAttributes(node, "content")} style={{ display: "grid", gap: 16 }}>
              {contentChildren}
            </div>
          </div>
        </section>
      );
    }
    case "stack":
      return (
        <div
          key={node.id}
          {...blockDataAttributes}
          {...getRegionDataAttributes(node, "content")}
          style={{ display: "flex", flexDirection: "column", gap: \`\${node.props.gap ?? 18}px\`, alignItems: \`\${node.props.align ?? "stretch"}\` }}
        >
          {contentChildren}
        </div>
      );
    case "grid":
      return (
        <div
          key={node.id}
          {...blockDataAttributes}
          {...getRegionDataAttributes(node, "content")}
          style={{ display: "grid", gap: \`\${node.props.gap ?? 18}px\`, gridTemplateColumns: \`repeat(\${node.props.columns ?? 3}, minmax(0, 1fr))\` }}
        >
          {contentChildren}
        </div>
      );
    case "hero": {
      const centered = node.props.align === "center";
      return (
        <section
          key={node.id}
          style={{
            borderRadius: 32,
            padding: "40px 32px",
            border: "1px solid var(--builder-border)",
            background: "linear-gradient(135deg, color-mix(in srgb, var(--builder-accent) 12%, white), rgba(255,255,255,0.95))",
            textAlign: centered ? "center" : "left",
          }}
        >
          <span style={{ display: "inline-flex", borderRadius: 999, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.8)", padding: "6px 12px", fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.24em", color: "var(--builder-muted)" }}>
            {\`\${node.props.eyebrow}\`}
          </span>
          <div style={{ marginTop: 24, display: "grid", gap: 16, maxWidth: 760, marginInline: centered ? "auto" : undefined }}>
            <h1 style={{ margin: 0, fontSize: 48, lineHeight: 1.05 }}>{\`\${node.props.title}\`}</h1>
            <p style={{ margin: 0, fontSize: 18, lineHeight: 1.7, color: "var(--builder-muted)" }}>{\`\${node.props.body}\`}</p>
          </div>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 28, justifyContent: centered ? "center" : "flex-start" }}>
            {buttonVariant(\`\${node.props.primaryLabel}\`, "primary")}
            {buttonVariant(\`\${node.props.secondaryLabel}\`, "secondary")}
          </div>
        </section>
      );
    }
    case "text":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.8)", padding: 24 }}>
          <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.75 }}>{\`\${node.props.body}\`}</p>
        </div>
      );
    case "button":
      return (
        <div key={node.id} style={{ padding: 16, borderRadius: 18, border: "1px dashed var(--builder-border)", background: "rgba(255,255,255,0.68)" }}>
          {buttonVariant(\`\${node.props.label}\`, \`\${node.props.variant}\`, Boolean(node.props.fullWidth))}
        </div>
      );
    case "featureGrid":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.82)", padding: 24 }}>
          <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          <div style={{ marginTop: 20 }}>{featureLines(\`\${node.props.features}\`)}</div>
        </div>
      );
    case "faqList": {
      const items = parseFaqItems(\`\${node.props.items}\`);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <div style={{ maxWidth: 760 }}>
            <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
            <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          </div>
          <div style={{ display: "grid", gap: 12, marginTop: 20 }}>
            {items.map((item, index) => (
              <div key={\`\${item.question}-\${index}\`} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "16px 18px" }}>
                <div style={{ display: "flex", alignItems: "start", gap: 12 }}>
                  <span style={{ width: 28, height: 28, borderRadius: 999, background: "color-mix(in srgb, var(--builder-accent) 10%, white)", color: "var(--builder-accent)", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700 }}>
                    {index + 1}
                  </span>
                  <div>
                    <p style={{ margin: 0, fontSize: 15, fontWeight: 700 }}>{item.question}</p>
                    <p style={{ margin: "8px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{item.answer}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      );
    }
    case "testimonialCard":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.86)", padding: 24 }}>
          <p style={{ margin: 0, fontSize: 28, lineHeight: 1.55 }}>"{\`\${node.props.quote}\`}"</p>
          <div style={{ marginTop: 20, paddingTop: 16, borderTop: "1px solid var(--builder-border)" }}>
            <p style={{ margin: 0, fontWeight: 700 }}>{\`\${node.props.author}\`}</p>
            <p style={{ margin: "6px 0 0", fontSize: 12, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--builder-muted)" }}>{\`\${node.props.role}\`}</p>
          </div>
        </div>
      );
    case "statCard":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 20 }}>
          <p style={{ margin: 0, fontSize: 14, color: "var(--builder-muted)" }}>{\`\${node.props.label}\`}</p>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "end", gap: 16, marginTop: 16 }}>
            <p style={{ margin: 0, fontSize: 42, fontWeight: 700 }}>{\`\${node.props.value}\`}</p>
            <span style={{ borderRadius: 999, padding: "6px 12px", background: "color-mix(in srgb, var(--builder-accent) 10%, white)", color: "var(--builder-accent)", fontSize: 12, fontWeight: 700 }}>
              {\`\${node.props.trend}\`}
            </span>
          </div>
        </div>
      );
    case "metricRow": {
      const metrics = parseMetricItems(\`\${node.props.metrics}\`);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 20 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 16 }}>
            <p style={{ margin: 0, fontWeight: 600 }}>{\`\${node.props.title}\`}</p>
            <span style={{ borderRadius: 999, border: "1px solid var(--builder-border)", padding: "4px 12px", fontSize: 11, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
              Summary
            </span>
          </div>
          <div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))" }}>
            {metrics.map((metric, index) => (
              <div
                key={\`\${metric.label}-\${index}\`}
                style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "16px 18px" }}
              >
                <p style={{ margin: 0, fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
                  {metric.label}
                </p>
                <p style={{ margin: "14px 0 0", fontSize: 32, fontWeight: 700 }}>{metric.value}</p>
                <p style={{ margin: "10px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{metric.meta}</p>
              </div>
            ))}
          </div>
        </div>
      );
    }
    case "activityFeed": {
      const entries = parseActivityEntries(\`\${node.props.entries}\`);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 20 }}>
          <div style={{ maxWidth: 760 }}>
            <p style={{ margin: 0, fontWeight: 600 }}>{\`\${node.props.title}\`}</p>
            <p style={{ margin: "10px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          </div>
          <div style={{ display: "grid", gap: 12, marginTop: 20 }}>
            {entries.map((entry, index) => (
              <div
                key={\`\${entry.title}-\${entry.meta}-\${index}\`}
                style={{
                  display: "grid",
                  gap: 12,
                  alignItems: "start",
                  borderRadius: 18,
                  border: "1px solid var(--builder-border)",
                  background: "var(--builder-surface)",
                  padding: "16px 18px",
                }}
              >
                <div style={{ display: "flex", alignItems: "start", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>
                  <div style={{ display: "flex", alignItems: "start", gap: 12 }}>
                    <span style={{ width: 12, height: 12, borderRadius: 999, background: "var(--builder-accent)", display: "inline-block", marginTop: 6 }} />
                    <div>
                      <p style={{ margin: 0, fontSize: 15, fontWeight: 700 }}>{entry.title}</p>
                      <p style={{ margin: "6px 0 0", fontSize: 11, color: "var(--builder-muted)", textTransform: "uppercase", letterSpacing: "0.16em" }}>{entry.meta}</p>
                    </div>
                  </div>
                  <span style={{ borderRadius: 999, padding: "6px 12px", background: "color-mix(in srgb, var(--builder-accent) 10%, white)", color: "var(--builder-accent)", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.14em" }}>
                    {entry.status}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      );
    }
    case "formCard":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "10px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          <div style={{ display: "grid", gap: 12, marginTop: 20 }}>
            <div style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "14px 16px", color: "var(--builder-muted)" }}>
              Email address
            </div>
            {buttonVariant(\`\${node.props.buttonLabel}\`, "primary", true)}
          </div>
        </div>
      );
    case "pricingCard":
      return (
        <div key={node.id} {...blockDataAttributes} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.88)", padding: 24 }}>
          <p style={{ margin: 0, fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--builder-muted)" }}>{\`\${node.props.tier}\`}</p>
          <div style={{ display: "flex", gap: 8, alignItems: "end", marginTop: 12 }}>
            <p style={{ margin: 0, fontSize: 42, fontWeight: 700 }}>{\`\${node.props.price}\`}</p>
            <span style={{ color: "var(--builder-muted)", paddingBottom: 6 }}>/ month</span>
          </div>
          <p style={{ margin: "16px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.tagline}\`}</p>
          <div {...getRegionDataAttributes(node, "content")} style={{ display: "grid", gap: 12, marginTop: 20 }}>
            {contentChildren}
          </div>
          <div {...getRegionDataAttributes(node, "actions")} style={{ display: "grid", gap: 12, marginTop: 20 }}>
            {actionChildren.length > 0 ? actionChildren : buttonVariant(\`\${node.props.cta}\`, "primary", true)}
          </div>
        </div>
      );
    case "logoGrid": {
      const logos = toLines(\`\${node.props.logos}\`);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <div style={{ maxWidth: 760 }}>
            <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
            <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          </div>
          <div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", marginTop: 20 }}>
            {logos.map((logo) => (
              <div key={logo} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "16px 18px", fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
                {logo}
              </div>
            ))}
          </div>
        </div>
      );
    }
    case "calloutCard": {
      const tone = \`\${node.props.tone ?? "accent"}\`;
      const backgrounds: Record<string, CSSProperties> = {
        accent: {
          background: "color-mix(in srgb, var(--builder-accent) 10%, white)",
          border: "1px solid color-mix(in srgb, var(--builder-accent) 20%, white)",
        },
        neutral: {
          background: "rgba(255,255,255,0.84)",
          border: "1px solid var(--builder-border)",
        },
        warning: {
          background: "#fff7ed",
          border: "1px solid #fdba74",
        },
      };

      return (
        <div key={node.id} style={{ borderRadius: 18, padding: 24, ...(backgrounds[tone] ?? backgrounds.accent) }}>
          <span style={{ display: "inline-flex", borderRadius: 999, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.8)", padding: "6px 12px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
            {\`\${node.props.eyebrow}\`}
          </span>
          <h3 style={{ margin: "16px 0 0", fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
        </div>
      );
    }
    case "ctaBanner": {
      const centered = \`\${node.props.align ?? "left"}\` === "center";

      return (
        <section
          key={node.id}
          {...blockDataAttributes}
          style={{
            borderRadius: 24,
            padding: "28px 24px",
            border: "1px solid var(--builder-border)",
            background: "linear-gradient(135deg, color-mix(in srgb, var(--builder-accent) 12%, white), rgba(255,255,255,0.92))",
            textAlign: centered ? "center" : "left",
          }}
        >
          <span style={{ display: "inline-flex", borderRadius: 999, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.8)", padding: "6px 12px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
            {\`\${node.props.eyebrow}\`}
          </span>
          <div style={{ marginTop: 18, display: "grid", gap: 12, maxWidth: 760, marginInline: centered ? "auto" : undefined }}>
            <h3 style={{ margin: 0, fontSize: 30, lineHeight: 1.15 }}>{\`\${node.props.title}\`}</h3>
            <p style={{ margin: 0, color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          </div>
          <div
            {...getRegionDataAttributes(node, "content")}
            style={{ display: "grid", gap: 12, marginTop: 20, maxWidth: 760, marginInline: centered ? "auto" : undefined }}
          >
            {contentChildren}
          </div>
          <div
            {...getRegionDataAttributes(node, "actions")}
            style={{ display: "grid", gap: 12, marginTop: 20, justifyItems: centered ? "center" : "stretch" }}
          >
            {actionChildren.length > 0 ? actionChildren : (
              <div style={{ display: "flex", gap: 12, flexWrap: "wrap", justifyContent: centered ? "center" : "flex-start" }}>
                {buttonVariant(\`\${node.props.primaryLabel}\`, "primary")}
                {buttonVariant(\`\${node.props.secondaryLabel}\`, "secondary")}
              </div>
            )}
          </div>
        </section>
      );
    }
    case "stepList": {
      const steps = parseStepItems(\`\${node.props.steps}\`);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <div style={{ maxWidth: 760 }}>
            <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
            <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          </div>
          <div style={{ display: "grid", gap: 12, marginTop: 20 }}>
            {steps.map((step) => (
              <div key={\`\${step.index}-\${step.title}\`} style={{ display: "grid", gridTemplateColumns: "auto minmax(0, 1fr)", gap: 14, alignItems: "start", borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "16px 18px" }}>
                <span style={{ width: 32, height: 32, borderRadius: 999, background: "var(--builder-accent)", color: "var(--builder-accent-contrast)", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 700 }}>
                  {step.index}
                </span>
                <div>
                  <p style={{ margin: 0, fontSize: 15, fontWeight: 700 }}>{step.title}</p>
                  <p style={{ margin: "8px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{step.detail}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      );
    }
    case "comparisonTable": {
      const { columns, rows } = parseTable(\`\${node.props.columns}\`, \`\${node.props.rows}\`);
      const columnCount = Math.max(columns.length, 1);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.86)", padding: 24 }}>
          <div style={{ maxWidth: 760 }}>
            <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
            <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          </div>
          <div style={{ overflow: "hidden", borderRadius: 18, border: "1px solid var(--builder-border)", marginTop: 20 }}>
            <div style={{ display: "grid", gridTemplateColumns: \`repeat(\${columnCount}, minmax(0, 1fr))\`, background: "var(--builder-surface)" }}>
              {columns.map((column, index) => (
                <div key={column} style={{ borderBottom: "1px solid var(--builder-border)", padding: "12px 16px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: index === 0 ? "var(--builder-foreground)" : "var(--builder-muted)" }}>
                  {column}
                </div>
              ))}
              {rows.flatMap((row, rowIndex) =>
                columns.map((column, columnIndex) => (
                  <div key={\`\${rowIndex}-\${column}-\${columnIndex}\`} style={{ borderBottom: "1px solid var(--builder-border)", padding: "12px 16px", fontSize: 14, color: columnIndex === 0 ? "var(--builder-foreground)" : "var(--builder-muted)", fontWeight: columnIndex === 0 ? 600 : 400 }}>
                    {row[columnIndex] ?? "--"}
                  </div>
                )),
              )}
            </div>
          </div>
        </div>
      );
    }
    case "infoList": {
      const items = parseInfoListItems(\`\${node.props.items}\`);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.title}\`}</h3>
          <div style={{ display: "grid", gap: 12, marginTop: 20 }}>
            {items.map((item, index) => (
              <div key={\`\${item.label}-\${index}\`} style={{ display: "flex", justifyContent: "space-between", alignItems: "start", gap: 16, borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "16px 18px" }}>
                <p style={{ margin: 0, fontWeight: 600 }}>{item.label}</p>
                <p style={{ margin: 0, color: "var(--builder-muted)", lineHeight: 1.7, textAlign: "right" }}>{item.value}</p>
              </div>
            ))}
          </div>
        </div>
      );
    }
    case "profileCard":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <div style={{ display: "flex", alignItems: "start", gap: 16 }}>
            <div style={{ width: 56, height: 56, borderRadius: 999, background: "var(--builder-accent)", color: "var(--builder-accent-contrast)", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 700 }}>
              {\`\${node.props.name}\`.slice(0, 1)}
            </div>
            <div>
              <h3 style={{ margin: 0, fontSize: 22 }}>{\`\${node.props.name}\`}</h3>
              <p style={{ margin: "6px 0 0", color: "var(--builder-muted)" }}>{\`\${node.props.role}\`}</p>
              <p style={{ margin: "4px 0 0", fontSize: 12, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>{\`\${node.props.detail}\`}</p>
            </div>
          </div>
          <p style={{ margin: "16px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.bio}\`}</p>
        </div>
      );
    case "chatInput":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, marginBottom: 16 }}>
            <p style={{ margin: 0, fontWeight: 600 }}>{\`\${node.props.label}\`}</p>
            <span style={{ borderRadius: 999, border: "1px solid var(--builder-border)", padding: "4px 12px", fontSize: 12, color: "var(--builder-muted)" }}>
              AI shell
            </span>
          </div>
          <div style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: 16 }}>
            <p style={{ margin: 0, color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.placeholder}\`}</p>
            <div style={{ display: "flex", justifyContent: "end", marginTop: 16 }}>{buttonVariant(\`\${node.props.buttonLabel}\`, "primary")}</div>
          </div>
        </div>
      );
    case "messageThread": {
      const transcript = parseTranscript(\`\${node.props.transcript}\`);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 20 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 16 }}>
            <p style={{ margin: 0, fontWeight: 600 }}>{\`\${node.props.title}\`}</p>
            <span style={{ borderRadius: 999, border: "1px solid var(--builder-border)", padding: "4px 12px", fontSize: 11, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--builder-muted)" }}>
              Thread
            </span>
          </div>
          <div style={{ display: "grid", gap: 12 }}>
            {transcript.map((entry, index) => (
              <div
                key={\`\${entry.sender}-\${index}\`}
                style={{
                  justifySelf: entry.isAssistant ? "start" : "end",
                  maxWidth: "88%",
                  borderRadius: 18,
                  padding: "12px 16px",
                  border: entry.isAssistant ? "1px solid var(--builder-border)" : undefined,
                  background: entry.isAssistant ? "rgba(255,255,255,0.92)" : "var(--builder-accent)",
                  color: entry.isAssistant ? "var(--builder-foreground)" : "var(--builder-accent-contrast)",
                }}
              >
                <p style={{ margin: "0 0 4px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: entry.isAssistant ? "var(--builder-muted)" : "inherit", opacity: entry.isAssistant ? 1 : 0.84 }}>
                  {entry.sender}
                </p>
                <p style={{ margin: 0, fontSize: 14, lineHeight: 1.7 }}>{entry.message}</p>
              </div>
            ))}
          </div>
        </div>
      );
    }
    case "dataTable": {
      const { columns, rows } = parseTable(\`\${node.props.columns}\`, \`\${node.props.rows}\`);
      const columnCount = Math.max(columns.length, 1);

      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.86)", padding: 20 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 16 }}>
            <p style={{ margin: 0, fontWeight: 600 }}>{\`\${node.props.title}\`}</p>
            <span style={{ borderRadius: 999, border: "1px solid var(--builder-border)", padding: "4px 12px", fontSize: 11, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--builder-muted)" }}>
              Table
            </span>
          </div>
          <div style={{ overflow: "hidden", borderRadius: 18, border: "1px solid var(--builder-border)" }}>
            <div style={{ display: "grid", gridTemplateColumns: \`repeat(\${columnCount}, minmax(0, 1fr))\`, background: "var(--builder-surface)" }}>
              {columns.map((column) => (
                <div key={column} style={{ borderBottom: "1px solid var(--builder-border)", padding: "12px 16px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
                  {column}
                </div>
              ))}
              {rows.flatMap((row, rowIndex) =>
                columns.map((column, columnIndex) => (
                  <div key={\`\${rowIndex}-\${column}-\${columnIndex}\`} style={{ borderBottom: "1px solid var(--builder-border)", padding: "12px 16px", fontSize: 14, color: "var(--builder-foreground)" }}>
                    {row[columnIndex] ?? "--"}
                  </div>
                )),
              )}
            </div>
          </div>
        </div>
      );
    }
    case "emptyState":
      return (
        <div key={node.id} style={{ borderRadius: 18, border: "1px dashed var(--builder-border)", background: "rgba(255,255,255,0.74)", padding: 24 }}>
          <span style={{ display: "inline-flex", borderRadius: 999, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.92)", padding: "6px 12px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
            Empty state
          </span>
          <h3 style={{ margin: "16px 0 0", fontSize: 30 }}>{\`\${node.props.title}\`}</h3>
          <p style={{ margin: "12px 0 0", maxWidth: 760, color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 20 }}>
            {buttonVariant(\`\${node.props.primaryLabel}\`, "primary")}
            {buttonVariant(\`\${node.props.secondaryLabel}\`, "secondary")}
          </div>
        </div>
      );
    case "workspaceHeader": {
      const tags = toLines(\`\${node.props.tags}\`);
      const actionsRegion = (
        <div
          {...getRegionDataAttributes(node, "actions")}
          style={{ display: "grid", gap: 12, justifyItems: "start", minWidth: 220 }}
        >
          {actionChildren.length > 0 ? actionChildren : (
            <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
              {buttonVariant(\`\${node.props.primaryLabel}\`, "primary")}
              {buttonVariant(\`\${node.props.secondaryLabel}\`, "secondary")}
            </div>
          )}
        </div>
      );

      return (
        <div key={node.id} {...blockDataAttributes} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.84)", padding: 24 }}>
          <div style={{ display: "flex", alignItems: "start", justifyContent: "space-between", gap: 16, flexWrap: "wrap" }}>
            <div style={{ maxWidth: 760 }}>
              <span style={{ display: "inline-flex", borderRadius: 999, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.92)", padding: "6px 12px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.16em", color: "var(--builder-muted)" }}>
                {\`\${node.props.eyebrow}\`}
              </span>
              <h3 style={{ margin: "16px 0 0", fontSize: 30 }}>{\`\${node.props.title}\`}</h3>
              <p style={{ margin: "12px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>{\`\${node.props.body}\`}</p>
            </div>
            {actionsRegion}
          </div>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 20 }}>
            {tags.map((tag) => (
              <span key={tag} style={{ borderRadius: 999, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: "6px 12px", fontSize: 12, color: "var(--builder-muted)" }}>
                {tag}
              </span>
            ))}
          </div>
          <div {...getRegionDataAttributes(node, "content")} style={{ display: "grid", gap: 12, marginTop: 20 }}>
            {contentChildren}
          </div>
        </div>
      );
    }
    case "sidebarShell": {
      const items = toLines(\`\${node.props.items}\`);
      const sidebarPosition = \`\${node.props.sidebarPosition ?? "left"}\` === "right" ? "right" : "left";
      const sidebarWidth = Number(node.props.sidebarWidth ?? 280);
      const gap = Number(node.props.gap ?? 18);
      const sidebarRegion = (
        <aside
          {...getRegionDataAttributes(node, "sidebar")}
          style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "var(--builder-surface)", padding: 18 }}
        >
          <p style={{ margin: 0, fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--builder-muted)" }}>
            Workspace rail
          </p>
          <p style={{ margin: "10px 0 0", fontWeight: 600 }}>{\`\${node.props.title}\`}</p>
          <div style={{ display: "grid", gap: 8, marginTop: 16 }}>
            {items.map((item) => {
              const active = item === \`\${node.props.highlight}\`;

              return (
                <div key={item} style={{ borderRadius: 16, padding: "10px 12px", color: active ? "var(--builder-accent-contrast)" : "var(--builder-muted)", background: active ? "var(--builder-accent)" : "transparent" }}>
                  {item}
                </div>
              );
            })}
          </div>
          <div style={{ display: "grid", gap: 12, marginTop: 16 }}>
            {sidebarChildren.length > 0 ? sidebarChildren : (
              <div style={{ borderRadius: 16, border: "1px dashed var(--builder-border)", padding: "14px 16px", color: "var(--builder-muted)", background: "rgba(255,255,255,0.72)", fontSize: 14, lineHeight: 1.7 }}>
                Add compact cards, text, or actions here for the supporting rail.
              </div>
            )}
          </div>
        </aside>
      );
      const contentRegion = (
        <section
          {...getRegionDataAttributes(node, "content")}
          style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.72)", padding: 18 }}
        >
          <div style={{ display: "flex", alignItems: "start", justifyContent: "space-between", gap: 12, flexWrap: "wrap", marginBottom: 16 }}>
            <div>
              <p style={{ margin: 0, fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--builder-muted)" }}>
                Main content
              </p>
              <p style={{ margin: "8px 0 0", color: "var(--builder-muted)", lineHeight: 1.7 }}>
                This region renders the primary application surface exported from the builder.
              </p>
            </div>
            <span style={{ borderRadius: 999, border: "1px solid var(--builder-border)", padding: "6px 12px", fontSize: 11, color: "var(--builder-muted)" }}>
              Multi-region shell
            </span>
          </div>
          <div style={{ display: "grid", gap: 16 }}>
            {contentChildren.length > 0 ? contentChildren : (
              <div style={{ borderRadius: 16, border: "1px dashed var(--builder-border)", padding: "18px 16px", color: "var(--builder-muted)", background: "rgba(255,255,255,0.8)", fontSize: 14, lineHeight: 1.7 }}>
                Add layout or content blocks to the sidebar shell in the builder to populate this workspace.
              </div>
            )}
          </div>
        </section>
      );

      return (
        <div key={node.id} {...blockDataAttributes} style={{ borderRadius: 18, border: "1px solid var(--builder-border)", background: "rgba(255,255,255,0.88)", padding: 18 }}>
          <div
            className={sidebarPosition === "right" ? "grid gap-4 lg:grid-cols-[minmax(0,1fr)_var(--builder-sidebar-width)]" : "grid gap-4 lg:grid-cols-[var(--builder-sidebar-width)_minmax(0,1fr)]"}
            style={{ ["--builder-sidebar-width" as string]: \`\${sidebarWidth}px\`, gap: \`\${gap}px\` }}
          >
            {sidebarPosition === "right" ? (
              <>
                {contentRegion}
                {sidebarRegion}
              </>
            ) : (
              <>
                {sidebarRegion}
                {contentRegion}
              </>
            )}
          </div>
        </div>
      );
    }
    default:
      return null;
  }
}

export function ProjectPage({ pageId }: { pageId: string }) {
  const page = project.pages.find((entry) => entry.id === pageId);

  if (!page) {
    return null;
  }

  const style = toBuilderThemeStyleVariables(project.theme);

  return (
    <main
      style={{
        ...style,
        minHeight: "100vh",
        background: "radial-gradient(circle at top left, rgba(15, 118, 110, 0.16), transparent 34%), linear-gradient(180deg, #fcfaf6 0%, #efe6d6 100%)",
        padding: "48px 24px 96px",
        color: "var(--builder-foreground)",
        fontFamily: project.theme.fontFamily,
      }}
    >
      <div style={{ maxWidth: 1180, margin: "0 auto", display: "grid", gap: 24 }}>
        {page.regions.header.map((rootId) => renderNode(rootId))}
        {page.regions.main.map((rootId) => renderNode(rootId))}
        {page.regions.footer.map((rootId) => renderNode(rootId))}
      </div>
    </main>
  );
}
`;
}

function createReadme(project: BuilderProject) {
  return `# ${project.name}

This starter was generated from Drag and Drop Studio.

## Scripts

- \`pnpm install\`
- \`pnpm dev\`
- \`pnpm build\`

## Included

- Multi-page route generation
- A schema-driven page renderer
- Theme values pulled from the builder project
- Editable page data in \`lib/project-data.ts\`

## Notes

This export keeps the schema and renderer explicit so a developer can continue refining the output instead of untangling opaque generated markup.
`;
}

function createProjectData(project: BuilderProject) {
  return `type PrimitiveValue = string | number | boolean;
type NodeProps = Record<string, PrimitiveValue>;

interface BuilderNode {
  id: string;
  type: string;
  props: NodeProps;
  regions: Record<string, string[]>;
}

interface BuilderPage {
  id: string;
  name: string;
  path: string;
  description: string;
  regions: {
    header: string[];
    main: string[];
    footer: string[];
  };
}

interface BuilderTheme {
  accent: string;
  accentContrast: string;
  background: string;
  surface: string;
  foreground: string;
  muted: string;
  radius: number;
  shadow: number;
  fontFamily: string;
}

interface BuilderProject {
  id: string;
  name: string;
  description: string;
  theme: BuilderTheme;
  pages: BuilderPage[];
  nodes: Record<string, BuilderNode>;
  updatedAt: string;
}

export const project: BuilderProject = ${JSON.stringify(project, null, 2)};
`;
}

function createRouteFile(pageId: string) {
  return `import { ProjectPage } from "@/lib/render-page";

export default function Page() {
  return <ProjectPage pageId="${pageId}" />;
}
`;
}

function createPackageJson(projectName: string) {
  return JSON.stringify(
    {
      name: projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      private: true,
      version: "0.1.0",
      scripts: {
        dev: "next dev",
        build: "next build --webpack",
        start: "next start",
      },
      dependencies: {
        next: "16.2.2",
        react: "19.2.4",
        "react-dom": "19.2.4",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4.2.2",
        "@types/node": "^20.19.37",
        "@types/react": "^19.2.14",
        "@types/react-dom": "^19.2.3",
        tailwindcss: "^4.2.2",
        typescript: "^5.9.3",
      },
    },
    null,
    2,
  );
}

function createTsConfig() {
  return `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
}

function createNextConfig() {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
}

function createPostCssConfig() {
  return `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`;
}

function createNextEnv() {
  return `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;
}

function pagePathToRouteFile(pathname: string) {
  if (pathname === "/") {
    return "app/page.tsx";
  }

  const segments = pathname.replace(/^\//, "").split("/").filter(Boolean);
  return `app/${segments.join("/")}/page.tsx`;
}

export function getStarterArchiveBaseName(project: BuilderProject) {
  return `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-starter`;
}

export function getStarterProjectFiles(project: BuilderProject): StarterProjectFile[] {
  const files: StarterProjectFile[] = [
    { path: "package.json", contents: createPackageJson(project.name) },
    { path: "tsconfig.json", contents: createTsConfig() },
    { path: "next.config.ts", contents: createNextConfig() },
    { path: "postcss.config.mjs", contents: createPostCssConfig() },
    { path: "next-env.d.ts", contents: createNextEnv() },
    { path: "README.md", contents: createReadme(project) },
    { path: ".env.example", contents: "# Add provider credentials here when you wire services in v2.\n" },
    { path: "app/layout.tsx", contents: createAppLayout() },
    { path: "app/globals.css", contents: createGlobalStyles() },
    { path: "lib/project-data.ts", contents: createProjectData(project) },
    { path: "lib/render-support.tsx", contents: createStarterRenderSupportFile() },
    { path: "lib/render-page.tsx", contents: createRendererFile() },
  ];

  for (const page of project.pages) {
    files.push({
      path: pagePathToRouteFile(page.path),
      contents: createRouteFile(page.id),
    });
  }

  return files;
}
